app = 'toki-pona-ai'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  DEBUG = 'false'
  DJANGO_SETTINGS_MODULE = 'config.settings.production'
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  port = 443
  handlers = ['tls', 'http']

[[services.ports]]
  port = 80
  handlers = ['http']
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static'

[deploy]
  release_command = "python manage.py migrate --noinput"
