app = "toki-pona-ai"
primary_region = "yyz" # Change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "false"
  ALLOWED_HOSTS = "*.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static"

[deploy]
  release_command = "python manage.py migrate"

[processes]
  app = "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
