# fly.toml app configuration file generated for toki-pona-ai-muddy-dew-4277 on 2025-03-15T21:15:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'toki-pona-ai-muddy-dew-4277'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEBUG = 'false'
  DJANGO_SETTINGS_MODULE = 'config.settings'
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[processes]
  web = 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
    force_https = true

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static'
